#This playbook create new instance, install tomcat on the server and deploy the war file
#Install ansible on jenkins
#Install boto packages on the jenkins 
#create AMI (which will contains jenkins user, public key with sudo privileges)
#Disable host key verification in ansible.cfg file
#Create user in AWS and configure the access key and secret key in jenkins server 
- name: ec2 launcher
  hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
  - name: Get Info Block
    block: 
      - name: Get Running instance Info
        ec2_instance_info:
        register: ec2info 
      - name: Print info
        debug: var="ec2info.instances"
  - name: launching ec2 instance
    ec2:
      instance_type: t2.micro
      key_name: sankar-devops
      image: ami-0741928d0ee9b6e66
      region: us-east-2
      group: launch-wizard-25
      count: 1
      wait: yes
      wait_timeout: 500
      instance_tags: 
            name: webserver
      assign_public_ip: yes
      vpc_subnet_id: subnet-eb3cd196
    register: ec2  
  - name: Add Instance IP into in-memory inventory file not into hosts file
    add_host: 
        hostname: "{{ item.public_ip }}"
        groupname: tomcat
        ansible_user: jenkins
        ansible_become: yes
    loop: "{{ ec2.instances }}"
  - name: Wait for 180 seconds before tomcat setup play execution    
    wait_for:
     timeout: 180
- name: tomcat setup
  hosts: tomcat
  become: true
  tasks:
  - name: Install Java
    command: yum install java-1.8.0-openjdk -y
    command: yum install java-1.8.0-openjdk-devel -y
  - lineinfile:
     path: /etc/profile
     line: 'export JRE_HOME=/usr/lib/jvm/jre'
  - lineinfile:
     path: /etc/profile
     line: 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk'
  - name: ensure a list of packages installed
    yum:
     name: "{{ packages }}"
    vars:
     packages:
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps
      - tomcat-docs-webapp
      - tomcat-javadoc
     state: present
  - name: Copy fil
    copy:
     src: /var/lib/jenkins/tomcat-users.xml
     dest: /usr/share/tomcat/conf/tomcat-users.xml
  - name: enable service tomcat
    systemd:
     name: tomcat
     enabled: yes
  - name: start service tomcat
    systemd:
     name: tomcat
     state: started
- name : Deploy latest war file from nexus to newly created tomcat server
  hosts: tomcat
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/gameoflife.war
    register: stat_result
  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/gameoflife.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /usr/share/tomcat/webapps/gameoflife
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/gameoflife
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://18.116.43.61:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife&p=war&v=LATEST
       dest: /usr/share/tomcat/webapps/gameoflife.war
  - name: Start Tomcat
    service: name=tomcat state=started
